task1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('tasks1.urls'))
]

tasks1/urls.py
"""Определяет схемы URL для tasks1"""

from django.urls import path
from . import views

app_name = 'tasks1'
urlpatterns = [
    path('', views.index, name='index'),
    path('tasks/', views.tasks, name='tasks'),
    path('tasks/<int:task_id>/', views.task, name='task'),
    path('new_task/', views.new_task, name='new_task'),
    path('new_entry/<int:task_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Определяет схемы URL для пользователей"""
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Включить URL авторизации по умолчанию.
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register')
]

tasks1/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class TodoList(models.Model):
    """Задача пользователя"""
    task_name = models.CharField(max_length=200)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        """Возвращает строковое представление модели."""
        return self.task_name


class Entry(models.Model):
    """Описание задачи"""
    task = models.ForeignKey(TodoList, on_delete=models.CASCADE)
    description = models.TextField()
    deadline = models.DateField(auto_now_add=False)
    status = models.BooleanField(default=False)
    priority = models.CharField(max_length=10, choices=(("high", "High"), ("medium", "Medium"), ("low", "Low")))
    
    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Возвращает строковое представление модели."""
        return f"{self.task}"
    

users/models.py
from django.db import models

# Create your models here.

tasks1/forms.py
from django import forms
from .models import TodoList, Entry


class TodoForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ['task_name']
        labels = {'task_name': ''}


class EntryForm(forms.ModelForm):

    class Meta:

        model = Entry
        fields = ['description', 'deadline', 'status', 'priority']
        labels = {'description': 'Описание', 'deadline': 'Дедлайн', 'status': 'Статус', 'priority': 'Приоритет'}
        widgets = {'description': forms.Textarea(attrs={'cols': 80}), 'deadline': forms.DateInput(attrs={'type': 'date'})}

tasks1/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import TodoList, Entry
from .forms import TodoForm, EntryForm
# Create your views here.


def index(request):
    """Домашняя страница приложения Task"""
    return render(request, 'tasks1/index.html')


@login_required
def tasks(request):
    """Выводит список задач"""
    tasks = TodoList.objects.filter(owner=request.user).order_by('task_name')
    context = {'tasks': tasks}
    return render(request, 'tasks1/tasks.html', context)


@login_required
def task(request, task_id):
    """Выводит одну задачу и ее подзадачи."""
    task = TodoList.objects.get(id=task_id)
    if task.owner != request.user:
        raise Http404
    entries = task.entry_set.order_by('deadline')
    context = {'task': task, 'entries': entries}
    return render(request, 'tasks1/task.html', context)


@login_required
def new_task(request):
    """Определяет новую задачу."""
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = TodoForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = TodoForm(data=request.POST)
        if form.is_valid():
            # form.save()
            new_task=form.save(commit=False)
            new_task.owner = request.user
            new_task.save()
            return redirect('tasks1:tasks')
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'tasks1/new_task.html', context)


@login_required
def new_entry(request, task_id):
    """Добавляет новую запись по конкретной задаче."""
    task = TodoList.objects.get(id=task_id)
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = EntryForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.task = task
            new_entry.save()
            return redirect('tasks1:task', task_id=task_id)
    # Вывести пустую или недействительную форму.
    context = {'task': task, 'form': form}
    return render(request, 'tasks1/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Редактирует существующую запись."""
    entry = Entry.objects.get(id=entry_id)
    task = entry.task
    if task.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = EntryForm(instance=entry)
    else:
        # Отправка данных POST; обработать данные.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('tasks1:task', task_id=task.id)
    context = {'entry': entry, 'task': task, 'form': form}
    return render(request, 'tasks1/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Регистрирует нового пользователя."""
    if request.method != 'POST':
        # Выводит пустую форму регистрации.
        form = UserCreationForm()
    else:
        # Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправление на домашнюю страницу.
            login(request, new_user)
            return redirect('tasks1:index')
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

tasks1/templates/tasks1/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Task manager</title>
    {% bootstrap_css %}
</head>
<body>
<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <a class="navbar-brand" href="{% url 'tasks1:index' %}">
        Task manager
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tasks1:tasks' %}">
                    Tasks
                </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text">Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <form action="{% url 'users:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-light">Log out</button>
                    </form>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
<main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</main>

{% bootstrap_javascript jquery='full' %}
</body>
</html>

tasks1/templates/tasks1/edit_entry.html
{% extends "tasks1/base.html" %}
{% block content %}
    <div class="row">
        <div class="col-md-6">
            <p><a href="{% url 'tasks1:task' task.id %}">{{ task }}</a></p>
            <p>Отредактировать описание:</p>
            <form action="{% url 'tasks1:edit_entry' entry.id %}" method='post'>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Сохранить изменения</button>
            </form>
        </div>
    </div>
{% endblock content %}

tasks1/templates/tasks1/index.html
{% extends "tasks1/base.html" %}
{% block content %}
    <div class="row">
        <div class="col-md-6">
            <p>Задачи</p>
        </div>
    </div>
{% endblock content %}

tasks1/templates/tasks1/new_entry.html
{% extends "tasks1/base.html" %}
{% block content %}
    <div class="row">
        <div class="col-md-6">
            <p><a href="{% url 'tasks1:task' task.id %}">{{ task }}</a></p>
            <p>Добавить описание:</p>
            <form action="{% url 'tasks1:new_entry' task.id %}" method='post'>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Добавить описание</button>
            </form>
        </div>
    </div>
{% endblock content %}

tasks1/templates/tasks1/new_task.html
{% extends "tasks1/base.html" %}
{% block content %}
    <div class="row">
        <div class="col-md-6">
            <p>Добавить новую задачу:</p>
            <form action="{% url 'tasks1:new_task' %}" method='post'>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Добавить задачу</button>
            </form>
        </div>
    </div>
{% endblock content %}

tasks1/templates/tasks1/task.html
{% extends 'tasks1/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-8">
            <p>Задание: {{ task }}</p>
            <p>Описание:</p>
            <p>
                <a href="{% url 'tasks1:new_entry' task.id %}" class="btn btn-primary">Добавить описание</a>
            </p>
            <ul class="list-unstyled">
                {% for entry in entries %}
                    <li>
                        <p>{{ entry.deadline|date:'M d, Y' }}</p>
                        <p>{{ entry.description|linebreaks }}</p>
                        {% if entry.status %}
                            <input type="checkbox" disabled checked /> <label>Выполнено</label>
                        {% else %}
                            <input type="checkbox" disabled /> <label>Не выполнено</label>
                        {% endif %}
                        <p>Приоритет задачи: --{{ entry.priority }}--</p>
                        <p>
                            <a href="{% url 'tasks1:edit_entry' entry.id %}" class="btn btn-secondary">Отредактировать</a>
                        </p>
                    </li>
                {% empty %}
                    <li>Тут пусто</li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock content %}

tasks1/templates/tasks1/tasks.html
{% extends "tasks1/base.html" %}
{% block content %}
    <div class="row">
        <div class="col-md-8">
            <h2>Задачи</h2>
            <ul class="list-group">
                {% for task in tasks %}
                    <li class="list-group-item">
                        <a href="{% url 'tasks1:task' task.id %}">{{ task }}</a>
                    </li>
                {% empty %}
                    <li class="list-group-item">No tasks ¯\_(ツ)_/¯</li>
                {% endfor %}
            </ul>
            <a href="{% url 'tasks1:new_task' %}" class="btn btn-primary mt-3">Добавить новую задачу</a>
        </div>
    </div>
{% endblock content %}